# Generated by Django 5.2.7 on 2025-10-08 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=15, unique=True)),
                ('dia_chi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NguyenPhuLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nguyen_phu_lieu', models.CharField(max_length=255)),
                ('don_vi_tinh', models.CharField(max_length=50)),
                ('so_luong_ton_kho', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nha_cung_cap', models.CharField(max_length=255)),
                ('thong_tin_lien_he', models.TextField(blank=True, null=True)),
                ('dia_chi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('don_gia_ban', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hinh_anh_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat_hang', models.DateTimeField(auto_now_add=True)),
                ('tong_gia_tri', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trang_thai', models.CharField(choices=[('CHO_XAC_NHAN', 'Chờ xác nhận'), ('DA_XAC_NHAN', 'Đã xác nhận'), ('DANG_GIAO', 'Đang giao'), ('HOAN_THANH', 'Hoàn thành'), ('DA_HUY', 'Đã hủy')], default='CHO_XAC_NHAN', max_length=20)),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='api.donhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sanpham')),
            ],
        ),
    ]
