# Generated by Django 5.2.7 on 2025-10-08 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhap', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.nhacungcap')),
                ('nhan_vien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_nhap', models.PositiveIntegerField()),
                ('gia_nhap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nguyen_phu_lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.nguyenphulieu')),
                ('phieu_nhap_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_nhap', to='api.phieunhapkho')),
            ],
        ),
    ]
